"""Update secret_answer column

Revision ID: 183dad6df4d7
Revises: b63b4b4e7fc7
Create Date: 2025-04-22 17:44:53.718781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183dad6df4d7'
down_revision = 'b63b4b4e7fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ps',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('UserName',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('secret_answer',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('secret_answer',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('UserName',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('ps',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
